In [1]:
import pandas as pd

path_to_geometry_data = "/Users/bencampbell/code/county_coverage/data/cleaner/centerlines_geo.json"

coordinates = pd.read_json(path_to_geometry_data)
coordinates

                                                 GEOMETRY
1       [[-85.6809503218, 38.1588670887], [-85.6810007...
2       [[-85.8012012237, 38.230563793], [-85.80136926...
3       [[-85.8050149882, 38.2289330216], [-85.8048524...
4       [[-85.6802054534, 38.2480671366], [-85.6798630...
5       [[-85.7420397977, 38.2118147709], [-85.7416475...
...                                                   ...
180232  [[-85.7085947307, 38.1432988961], [-85.7081273...
180233  [[-85.4509340541, 38.2704398554], [-85.4510619...
180234  [[-85.4517479832, 38.2709209675], [-85.4518987...
180235  [[-85.4527137888, 38.2712854193], [-85.4523040...
180236  [[-85.4517479832, 38.2709209675], [-85.4515231...

[35039 rows x 1 columns]

In [43]:
# get enclosing box for each coodinate list
inf = float(inf)

def get_box(coordinates):
    longitude_max = -inf
    longitude_min = inf
    latitude_max = -inf
    latitude_min = inf
    
    for longitude, latitude in coordinates:
        if longitude < longitude_min:
            longitude_min = longitude
        if longitude > longitude_max:
            longitude_max = longitude
        if latitude < latitude_min:
            latitude_min = latitude
        if latitude > latitude_max:
            latitude_max = latitude
    return {'longitude_min': longitude_min,
            'longitude_max': longitude_max, 
            'latitude_min': latitude_min,
            'latitude_max': latitude_max}

boxes = pd.DataFrame.from_dict(coordinates.GEOMETRY.apply(get_box).to_dict(), orient='index')
boxes

        longitude_min  longitude_max  latitude_min  latitude_max
1          -85.681235     -85.680950     38.158161     38.158867
2          -85.801369     -85.801201     38.229343     38.230564
3          -85.805015     -85.804692     38.227538     38.228933
4          -85.680205     -85.679863     38.247608     38.248067
5          -85.742040     -85.741648     38.211815     38.211969
...               ...            ...           ...           ...
180232     -85.708595     -85.702073     38.137379     38.143299
180233     -85.451748     -85.450934     38.270440     38.270921
180234     -85.452714     -85.451748     38.270921     38.271285
180235     -85.452714     -85.449049     38.270440     38.272728
180236     -85.451748     -85.450588     38.270921     38.271801

[35039 rows x 4 columns]

In [36]:

pd.concat((coordinates, boxes), axis=1)

,GEOMETRY,longitude_min,longitude_max,latitude_min,latitude_max
1,"[[-85.6809503218, 38.1588670887], [-85.6810007...",-85.681235,-85.680950,38.158161,38.158867
2,"[[-85.8012012237, 38.230563793], [-85.80136926...",-85.801369,-85.801201,38.229343,38.230564
3,"[[-85.8050149882, 38.2289330216], [-85.8048524...",-85.805015,-85.804692,38.227538,38.228933
4,"[[-85.6802054534, 38.2480671366], [-85.6798630...",-85.680205,-85.679863,38.247608,38.248067
5,"[[-85.7420397977, 38.2118147709], [-85.7416475...",-85.742040,-85.741648,38.211815,38.211969
...,...,...,...,...,...
180232,"[[-85.7085947307, 38.1432988961], [-85.7081273...",-85.708595,-85.702073,38.137379,38.143299
180233,"[[-85.4509340541, 38.2704398554], [-85.4510619...",-85.451748,-85.450934,38.270440,38.270921
180234,"[[-85.4517479832, 38.2709209675], [-85.4518987...",-85.452714,-85.451748,38.270921,38.271285
180235,"[[-85.4527137888, 38.2712854193], [-85.4523040...",-85.452714,-85.449049,38.270440,38.272728
180236,"[[-85.4517479832, 38.2709209675], [-85.4515231...",-85.451748,-85.450588,38.270921,38.271801